### ISSUE TITLE
Complexity v. null model

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_svd_networks#1]
The always wise @gvdr has suggested that we could compare SVD entropy to its distribution after a null model - that's a good idea, I'll probably write the code this afternoon, in anticipation of a revision.

**Comment by tpoisot** [comment]
So, after trying two null models (connectance and degree distribution), here are the results:

![nullmodel_histogram](https://user-images.githubusercontent.com/579329/98004468-f9afbb00-1dbd-11eb-8e0e-f2fa5ed99e13.png)

This is the z-score of SVD entropy after 999 random draws of equally sized networks. So networks have (i) high absolute complexity value but (ii) tend to be a little less complex than they could. These are the three groups on which we performed the ANOVA.

Just to get a sense of what drives the low values, I did this:

![nullmodel_richness](https://user-images.githubusercontent.com/579329/98004671-3380c180-1dbe-11eb-9ce4-272788f7992d.png)

This is the logistic of the z-score, where 0 .5 is "as complex as we expect", lower means less complex, and higher means more. Of all the things I tried, richness (here specifically the log-2 of richness) is the only one that has any relationship with the excess of complexity. 

This is an interesting result, because the conclusion is, *larger networks are less complex than they could be*.

It doesn't change the message of the paper (on a scale from 0 to 1, ecological networks are really complex), but it adds a little bit of nuance.

@gvdr do you have additional things you would like to see in this figure? Please consider this an invitation to join us on the paper, if you want to add a bit of discussion on this point.

**Comment by gvdr** [comment]
Kia ora! Amazing to see the fast prototyping.
Happy to chip in.

The reading of "complexity" that makes sense for me is one where it is indeed possible to distinguish between simple and complex objects: that is, we may want to draw a line somewhere. Directly comparing observed food webs is a way of doing this, but requires splitting somewhat artificially the ensemble of ecological networks between simple and complex. An alternative approach is to define complexity against a null model of what the ecological web could have been. Thus, the definition of complexity becomes dependent upon the choice of a null model: the same ecological network can be complex with respect to null1 and not complex with respect to null2. The results produced in this issues show that what we evaluate the complexity / simplicity against does matter.

Now, my gut feeling (and I can try to make a convincing argument but not prove it mathematically*) is that comparing SVD entropy of ecological networks against null1 and null2 is a tough, extremely conservative, demand.

I wonder whether applying a more constrained randomization (i.e., preserving even more of the structure) would make a difference. One idea would be, as we are already using SVD, to obtain draws from RDPG reconstruction of the observed bipartite matrices (see the code I sent you for the other project) and compute the SVD entropy of those. I bet it's less a conservative definition of complexity.

* Alas!, I don't think we know much from the theoretical side about the SVD entropy of random graphs (even less about the SVD entropy of random *bipartite* graphs, and the bipartite here is relevant). What *I* know is:
1. From (my take on) this Severini et al. [theorem](https://www.sciencedirect.com/science/article/pii/S0024379510003368) plus Passerini and Severini theorem 3 [here](https://arxiv.org/pdf/0812.2597v1.pdf) is that large enough Gnp (null1) graphs do obtain maximum von Neumann entropy (which is not SVD entropy, but maybe close enough to be relevant?). Thus, this makes the result that "larger networks are less complex than they could be" even more nuanced.
2. Gnp and configuration graphs (null1 and null2) are maximum entropy random graphs model. What is the relation between maximum entropy graphs under different constraint and SVD entropy? Ah! Good question!

**Comment by tpoisot** [comment]
@gvdr I have opened a pull request, (#3) - very much looking forward to your feedback + welcoming you as co-author if you want. Gonna close this issue now.
